live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@LinuxMint"
opacity = 0.95
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 130
lines = 35

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 11

[font.normal]
family = "Monospace"
style = "Regular"

[font.bold]
family = "Monospace"
style = "Medium"

[font.italic]
family = "Monospace"
style = "Italic"

[font.bold_italic]
family = "Monospace"
style = "Medium Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>	"
save_to_clipboard = true

[cursor]
style = "Block"
vi_mode_style = "Block"
unfocused_hollow = true
thickness = 0.1

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
    { key = "Paste", action = "Paste" },
    { key = "Copy", action = "Copy" },
    { key = "L", mods = "Control", action = "ClearLogNotice" },
    { key = "L", mods = "Control", mode = "~Vi", chars = "\f" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "F", mods = "Control|Shift", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward" },
    { key = "C", mods = "Control|Shift", mode = "Vi", action = "ClearSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[colors]
indexed_colors = [
    { index = 16, color = "#FAB387" },
    { index = 17, color = "#F5E0DC" },
]

[colors.primary]
background = "#171423"
foreground = "#9F9FA1"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#2D283F"
red = "#ED2261"
green = "#1FA91B"
yellow = "#8DDC20"
blue = "#487DF4"
magenta = "#8D35C9"
cyan = "#3BDEED"
white = "#9E9EA0"

[colors.bright]
black = "#59516A"
red = "#F0729A"
green = "#53AA5E"
yellow = "#B2DC87"
blue = "#A9BCEC"
magenta = "#AD81C2"
cyan = "#9DE3EB"
white = "#A288F7"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"
